# Generated by Django 3.2.20 on 2023-11-26 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpal_app', '0002_auto_20231122_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone',
            field=models.CharField(default=False, max_length=12),
        ),
    ]
