# Generated by Django 3.2.20 on 2023-11-26 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpal_app', '0004_auto_20231126_1642'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registered_users',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(default=False, max_length=15),
        ),
    ]
