# Generated by Django 3.2.20 on 2023-12-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pmpal_app', '0006_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
